spring.application.name=DocBookApp

server.port=${PORT:8085}
server.servlet.session.persistent=false

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/DocbookDB}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root@2005}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Explicit Hibernate Dialect Fix for Cloud Deployment
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.jwtSecret=${JWT_SECRET:Aditya@hepJFROXcyu1XqolVEXkwj/5byy59wkTuKdoWZbEy04PygDtEcaqvr4zPco#}
jwt.accessTokenExpiration=86400000
jwt.refreshTokenExpiration=604800000

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:446602586003-hrevb2o1j5197eru43rp5lqnn6kqsfp5.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_live_TGYFk7tquuLQeL}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:hcnqQKWpXx7autI9V0DLOxSr}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:rajshrivastav1456@gmail.com}
spring.mail.password=${MAIL_PASSWORD:yqpr tqcv mqbf mgyc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend Connection URL
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

# Large Base64 Payload & File Uploads
server.tomcat.max-http-form-post-size=-1
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.security=INFO


